### ISSUE TITLE
Brug java.util.Observable/Observer

### ISSUE THREAD

**Issue by zealand-andp** [ThunderGrove/mvvmDemo#1]
Prøv at lade din Model nedarve fra java.util.Observable og benytte dens indbyggede funktionalitet til at facilitere notifkation af Observer'e. Du skal benytte metoderne (setChanged og notifyObservers) der ligner dem du selv har lavet, men klassen sørger for at vedligeholde en liste af Observer'e samt give dem besked når der er opdateringer.

I dit View skal du så implementere en Observer som tilmelder sig din Model. Observer'ens update-metode skal så stå for at opdatere din label.

**Comment by ThunderGrove** [comment]
Done.
